services:
  web:
    image: odoo:17
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=database
      - PORT=5432
      - USER=odoo_user
      - PASSWORD=odoo_password
    depends_on:
      - database

  database:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

volumes:
  odoo_db_data:
  odoo_data: