services:
  odoo:
    image: odoo:17
    container_name: odoo_17_odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo_user
      - PASSWORD=odoo_password
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: odoo_17_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo_17_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  odoo_data:
  postgres_data:
  pgadmin_data: