services:
  database:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: