[options]
addons_path = /home/manh/Project/Self/odoo_boilerplate/extra-addons,/home/manh/Project/Self/odoo_boilerplate/src/addons
db_host = localhost
db_port = 5432
db_user = admin
db_password = admin
admin_passwd = $pbkdf2-sha512$600000$JWRMqXWu9b4XYmyNsZaydg$JiEN08ZDX9goCm8U6EidpCa/jF0NednN6qqTO1QlJ5/mJdZFYFbsOV4pjzDUOKf0Mui/ChrKpLLJT/reeI5iiA

